---
title: "ödev"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

df <- data.frame(
  a = c(47.8,46.4,46.3,45.1,47.6,52.5,51.2,49.8,48.1,45,51.2,48.5,52.1,48.2,49.6,50.7,47.2,53.3,46.2,46.3),
  b = c(48.8,47.3,46.8,45.3,48.5,53.2,53,50,50.8,47,51.4,49.2,52.8,48.9,50.4,51.7,47.7,54.6,47.5,47.6),
  c = c(49,47.7,47.8,46.1,48.9,53.3,54.3,50.3,52.3,47.3,51.6,53,53.7,49.3,51.2,52.7,48.4,55.1,48.1,51.3)
  d = c()

)

df








```



49.7,48.4,48.5,47.2,49.3,53.7,54.5,52.7,54.4,48.3,51.9,55.5,55,49.8,51.8,53.3,49.5,55.3,48.4, 51.8









```{r}
df <- ryas
df <- data.frame ( yasgrup = c (yas$yasgrup),
                   degerler = c (yas$degerler)
)

df
summary(df)
boxplot(yas2)
library("dplyr")
glimpse(yas2)
summary(df)
profiling_num(df$yas)
sum(is.na(df))


df
plot(deger ~ yas, data = df,
     pch = 10, cex = 1, main = "Satislar vs TV Harcamalari")

pairs(yas2)

library("ade4")
chart.Correlation(yas2, histogram =  TRUE, pch = 19)

library(psych)
describe(yas2)

library(tidyverse)
ggplot(yas2, aes(Sepal.Length, Sepal.Width)) +
  geom_point(size = 2, 
             shape = 21, 
             stroke = 1,
             color = "black",
             fill = "orange") +
  geom_smooth(color = "red")

library(GGally)



cor(yas2)
cor.test(df$mpg, df$wt)
plot(yas2)

ggcorr(yas2)
ggpairs(yas2)

t.test(yas2$sekizyas, mu = 170, alternative = "less", conf.level = 0.95)

shapiro.test(yas2$sekizyas)
shapiro.test(yas2$sekizbucukyas)
shapiro.test(yas2$dokuzyas)

A <- data.frame(degerler = yas2$sekizyas , sinif = "A")
B <- data.frame(degerler = yas2$sekizbucukyas , sinif = "B")

AB <- rbind(A,B)
AB
library(car)

leveneTest(AB$degerler ~ AB$sinif, center = mean)

t.test(AB$degerler~AB$sinif, var.equal = TRUE)

t.test(AB$degerler ~ AB$sinif, paired = TRUE)


ryas %>% group_by(yas) %>%
  summarise(mean(deger), median(deger), sd(deger))
bartlett.test(deger ~ yas, data = ryas)

aov(deger ~ yas, data = ryas)

summary(aov(deger ~ yas, data = ryas))

library(ggpubr)
ggscatter(yas2, x = "sekizyas", y ="sekizbucukyas",
          add = "reg.line", #grafile regresyon doğrusu ekler 
          conf.int = TRUE,
          cor.coef = TRUE, #kolerasyon gösterir grafikte
          cor.method = "pearson")

library(PerformanceAnalytics)

chart.Correlation(yas2, histogram = TRUE, pch = 19)




```


```{r}

df <- panelex
summary(df)



```




